//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RestaurantItem()
        {
            this.ItemAlerts = new HashSet<ItemAlert>();
        }
    
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public int ItemId { get; set; }
        public int StockCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemAlert> ItemAlerts { get; set; }
        public virtual Item Item { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
