//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDay
    {
        public int Id { get; set; }
        public int PersonID { get; set; }
        public int DayOfWeek { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
